FROM jenkins/jnlp-agent-terraform

ENV TFSEC_VERSION=v1.1.3

RUN apk upgrade && apk --no-cache add bash git libc-dev libffi-dev musl-dev
RUN apk add --update python3-dev py3-pip gcc
RUN pip3 install --no-cache --upgrade pip setuptools wheel
RUN pip3 install checkov --no-cache-dir

# Install tfsec
RUN wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64    && chmod +x ./tfsec   && mv ./tfsec /usr/local/bin/tfsec

